SET time_zone = "+00:00";

CREATE DATABASE IF NOT EXISTS `epytodo`;
USE `epytodo`;

CREATE TABLE IF NOT EXISTS `user` (
  `id` INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `email` VARCHAR(64) UNIQUE NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `firstname` VARCHAR(64) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `todo` (
  `id` INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(64) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `due_time` DATETIME NOT NULL,
  `status` VARCHAR(22) NOT NULL DEFAULT "not started",
  `user_id` INT(11) UNSIGNED NOT NULL
);

ALTER TABLE `todo`
  ADD FOREIGN KEY (`user_id`) REFERENCES `user`(`id`);

CREATE USER IF NOT EXISTS 'epytodo'@'localhost' IDENTIFIED BY 'password';
GRANT ALL ON epytodo.* TO 'epytodo'@'localhost';
FLUSH PRIVILEGES;