CREATE TABLE `user` (
  `id` INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `email` VARCHAR(64) UNIQUE NOT NULL,
  `name` VARCHAR(64) NOT NULL,
  `firstname` VARCHAR(64) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE `todo` (
  `id` INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(64) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `due_time` DATETIME NOT NULL,
  `status` VARCHAR(22) NOT NULL DEFAULT "not started",
  `user_id` INT(11) UNSIGNED NOT NULL
);